// <auto-generated />
using System;
using InfoWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoWeb.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230706211639_avancandoModels01")]
    partial class avancandoModels01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoWeb.Models.CentroCusto", b =>
                {
                    b.Property<int>("cen_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cen_codigo"));

                    b.Property<string>("cen_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("cen_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("cen_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("cen_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("cen_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("cen_codigo");

                    b.ToTable("CentrosCusto");
                });

            modelBuilder.Entity("InfoWeb.Models.ConfigPerfilLoja", b =>
                {
                    b.Property<int>("cpl_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cpl_codigo"));

                    b.Property<string>("cpl_valor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("pfl_codigo")
                        .HasColumnType("int");

                    b.Property<int>("usu_codigo")
                        .HasColumnType("int");

                    b.HasKey("cpl_codigo");

                    b.ToTable("ConfigsPerfilLoja");
                });

            modelBuilder.Entity("InfoWeb.Models.ConfigPermissaoUsuario", b =>
                {
                    b.Property<int>("cpu_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cpu_codigo"));

                    b.Property<string>("cpu_valor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("pmu_codigo")
                        .HasColumnType("int");

                    b.Property<int>("usu_codigo")
                        .HasColumnType("int");

                    b.HasKey("cpu_codigo");

                    b.ToTable("ConfigsPermissaoUsuario");
                });

            modelBuilder.Entity("InfoWeb.Models.ContaPagar", b =>
                {
                    b.Property<int>("pag_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pag_codigo"));

                    b.Property<int?>("cen_codigo")
                        .HasColumnType("int");

                    b.Property<int>("fpg_codigo")
                        .HasColumnType("int");

                    b.Property<int>("loj_codigo")
                        .HasColumnType("int");

                    b.Property<bool>("pag_debtesouraria")
                        .HasColumnType("bit");

                    b.Property<string>("pag_documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("pag_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtcadastro")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtcomp")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtlanc")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtpag")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtvenc")
                        .HasColumnType("date");

                    b.Property<string>("pag_historico")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<TimeSpan>("pag_hora")
                        .HasColumnType("time");

                    b.Property<string>("pag_id_refs")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("pag_numNfe")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("pag_situacao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("pag_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("pag_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<decimal>("pag_vlracresc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrdesc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrdoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrmulta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrpagar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrpago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("pes_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("tes_codigo")
                        .HasColumnType("int");

                    b.HasKey("pag_codigo");

                    b.HasIndex("cen_codigo");

                    b.HasIndex("fpg_codigo");

                    b.ToTable("ContasPagar");
                });

            modelBuilder.Entity("InfoWeb.Models.CstCofins", b =>
                {
                    b.Property<int>("cof_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cof_codigo"));

                    b.Property<int>("cof_cst_inversa")
                        .HasColumnType("int");

                    b.Property<string>("cof_descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("cof_tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("cof_codigo");

                    b.ToTable("CstsCofins");
                });

            modelBuilder.Entity("InfoWeb.Models.CstIcms", b =>
                {
                    b.Property<int>("icm_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("icm_codigo"));

                    b.Property<string>("icm_descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("icm_codigo");

                    b.ToTable("CstsIcms");
                });

            modelBuilder.Entity("InfoWeb.Models.CstIpi", b =>
                {
                    b.Property<int>("ipi_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ipi_codigo"));

                    b.Property<int>("ipi_cst_inversa")
                        .HasColumnType("int");

                    b.Property<string>("ipi_descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ipi_tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ipi_codigo");

                    b.ToTable("CstsIpi");
                });

            modelBuilder.Entity("InfoWeb.Models.CstPis", b =>
                {
                    b.Property<int>("pis_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pis_codigo"));

                    b.Property<int>("pis_cst_inversa")
                        .HasColumnType("int");

                    b.Property<string>("pis_descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("pis_tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("pis_codigo");

                    b.ToTable("CstsPis");
                });

            modelBuilder.Entity("InfoWeb.Models.Estoque", b =>
                {
                    b.Property<int>("est_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("est_codigo"));

                    b.Property<int>("cfop_ent_codigo")
                        .HasColumnType("int");

                    b.Property<int>("cfop_sai_codigo")
                        .HasColumnType("int");

                    b.Property<int>("cof_ent_codigo")
                        .HasColumnType("int");

                    b.Property<int>("cof_sai_codigo")
                        .HasColumnType("int");

                    b.Property<decimal>("est_cof_perc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("est_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("est_dtcadastro")
                        .HasColumnType("date");

                    b.Property<decimal>("est_estoque")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_estoque_avariado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_estoque_reservado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_estoque_usado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("est_imposto")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("est_ipi_perc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_pis_perc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_preco8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precoliquido8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_precopromocional8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("est_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("est_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<decimal>("est_vlrdesconto1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_vlrdesconto2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_vlrdesconto3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_vlrdesconto4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_vlrdesconto5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_vlrdesconto6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_vlrdesconto7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("est_vlrdesconto8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("icms_codigo")
                        .HasColumnType("int");

                    b.Property<int>("ipi_ent_codigo")
                        .HasColumnType("int");

                    b.Property<int>("ipi_sai_codigo")
                        .HasColumnType("int");

                    b.Property<int>("loj_codigo")
                        .HasColumnType("int");

                    b.Property<int>("pis_ent_cod")
                        .HasColumnType("int");

                    b.Property<int>("pis_sai_cod")
                        .HasColumnType("int");

                    b.Property<int>("pro_codigo")
                        .HasColumnType("int");

                    b.HasKey("est_codigo");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("InfoWeb.Models.FormaPag", b =>
                {
                    b.Property<int>("fpg_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fpg_codigo"));

                    b.Property<string>("fpg_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("fpg_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("fpg_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("fpg_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("fpg_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("fpg_codigo");

                    b.ToTable("FormasPag");
                });

            modelBuilder.Entity("InfoWeb.Models.GrupoPro", b =>
                {
                    b.Property<int>("gru_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gru_codigo"));

                    b.Property<string>("gru_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("gru_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("gru_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("gru_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("gru_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("gru_codigo");

                    b.ToTable("GruposPro");
                });

            modelBuilder.Entity("InfoWeb.Models.Ica", b =>
                {
                    b.Property<int>("ica_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ica_codigo"));

                    b.Property<string>("ica_descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ica_codigo");

                    b.ToTable("Icas");
                });

            modelBuilder.Entity("InfoWeb.Models.Marca", b =>
                {
                    b.Property<int>("mar_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mar_codigo"));

                    b.Property<string>("mar_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("mar_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("mar_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("mar_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("mar_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("mar_codigo");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("InfoWeb.Models.Municipio", b =>
                {
                    b.Property<int>("mun_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mun_codigo"));

                    b.Property<string>("mun_nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("mun_uf")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("mun_codigo");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("InfoWeb.Models.NafCfop", b =>
                {
                    b.Property<int>("cfo_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cfo_codigo"));

                    b.Property<int>("cfo_cst_inversa")
                        .HasColumnType("int");

                    b.Property<string>("cfo_descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("cfo_tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("cfo_codigo");

                    b.ToTable("NafsCfop");
                });

            modelBuilder.Entity("InfoWeb.Models.OpcaoPerfilLoja", b =>
                {
                    b.Property<string>("opl_descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("opl_valor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("pfl_codigo")
                        .HasColumnType("int");

                    b.ToTable("OpcoesPerfilLoja");
                });

            modelBuilder.Entity("InfoWeb.Models.OpcaoPermissaoUsuario", b =>
                {
                    b.Property<string>("opu_descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("opu_valor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("pmu_codigo")
                        .HasColumnType("int");

                    b.ToTable("OpcoesPermissaoUsuario");
                });

            modelBuilder.Entity("InfoWeb.Models.PerfilLoja", b =>
                {
                    b.Property<int>("pfl_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pfl_codigo"));

                    b.Property<int>("mds_codigo")
                        .HasColumnType("int");

                    b.Property<string>("pfl_definicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("pfl_descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("pfl_tipovalor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("pfl_vlrdefault")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("pfl_codigo");

                    b.ToTable("PerfisLoja");
                });

            modelBuilder.Entity("InfoWeb.Models.PermissaoUsuario", b =>
                {
                    b.Property<int>("pmu_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pmu_codigo"));

                    b.Property<int>("mds_codigo")
                        .HasColumnType("int");

                    b.Property<string>("pmu_definicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("pmu_descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("pmu_tipovalor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("pmu_vlrdefault")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("pmu_codigo");

                    b.ToTable("PermissoesUsuario");
                });

            modelBuilder.Entity("InfoWeb.Models.Pessoa", b =>
                {
                    b.Property<int>("pes_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pes_codigo"));

                    b.Property<int>("mun_codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("pag_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("pag_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("pag_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<string>("pes_bairro")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("pes_celular")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("pes_cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("pes_complemento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("pes_cpf_cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("pes_email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("pes_endereco")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("pes_fantasia")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("pes_fone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("pes_identidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("pes_nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("pes_numero")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("pes_observacoes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("pes_situacao")
                        .HasColumnType("bit");

                    b.Property<string>("pes_tabela")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("pes_tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("pes_codigo");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("InfoWeb.Models.Produto", b =>
                {
                    b.Property<int>("pro_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pro_codigo"));

                    b.Property<DateTime>("cen_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("cen_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("cen_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("cen_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<int>("gru_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("ica_codigo")
                        .HasColumnType("int");

                    b.Property<int>("mar_codigo")
                        .HasColumnType("int");

                    b.Property<int>("pes_codigo")
                        .HasColumnType("int");

                    b.Property<string>("pro_codigoean")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("pro_descfiscal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("pro_descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("pro_genero")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("pro_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pro_ncm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("pro_observacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("pro_prccompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pro_prccomprant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pro_prccusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pro_prctransf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("pro_referencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("pro_situacao")
                        .HasColumnType("bit");

                    b.Property<string>("unidade")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("pro_codigo");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("InfoWeb.Models.ProdutoLotacao", b =>
                {
                    b.Property<int>("lot_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lot_codigo"));

                    b.Property<decimal>("lot_qtd_und_compra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("pes_codigo")
                        .HasColumnType("int");

                    b.Property<int>("pro_codigo")
                        .HasColumnType("int");

                    b.HasKey("lot_codigo");

                    b.ToTable("ProdutosLotacao");
                });

            modelBuilder.Entity("InfoWeb.Models.Tesouraria", b =>
                {
                    b.Property<int>("tes_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tes_codigo"));

                    b.Property<int?>("cen_codigo")
                        .HasColumnType("int");

                    b.Property<int>("fpg_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("loj_codigo")
                        .HasColumnType("int");

                    b.Property<int>("pag_codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("tes_data")
                        .HasColumnType("date");

                    b.Property<DateTime>("tes_datavenc")
                        .HasColumnType("date");

                    b.Property<string>("tes_doctitulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("tes_documento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("tes_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("tes_dtcadastro")
                        .HasColumnType("date");

                    b.Property<string>("tes_historico")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<TimeSpan>("tes_hora")
                        .HasColumnType("time");

                    b.Property<string>("tes_tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("tes_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("tes_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<decimal>("tes_valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("tes_codigo");

                    b.ToTable("Tesourarias");
                });

            modelBuilder.Entity("InfoWeb.Models.Usuario", b =>
                {
                    b.Property<int>("usu_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usu_codigo"));

                    b.Property<int>("loj_codigo")
                        .HasColumnType("int");

                    b.Property<string>("usu_apelido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("usu_cargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("usu_cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("usu_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("usu_dtcadastro")
                        .HasColumnType("date");

                    b.Property<string>("usu_email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("usu_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("usu_is_staff")
                        .HasColumnType("bit");

                    b.Property<string>("usu_nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("usu_situacao")
                        .HasColumnType("bit");

                    b.Property<int>("usu_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("usu_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("usu_codigo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("InfoWeb.Models.ContaPagar", b =>
                {
                    b.HasOne("InfoWeb.Models.CentroCusto", null)
                        .WithMany()
                        .HasForeignKey("cen_codigo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InfoWeb.Models.FormaPag", null)
                        .WithMany()
                        .HasForeignKey("fpg_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
