// <auto-generated />
using System;
using InfoWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoWeb.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230705212025_avancando6-atualizacao")]
    partial class avancando6atualizacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoWeb.Models.CentroCusto", b =>
                {
                    b.Property<int>("cen_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cen_codigo"));

                    b.Property<string>("cen_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("cen_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("cen_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("cen_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("cen_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("cen_codigo");

                    b.ToTable("CentrosCusto");
                });

            modelBuilder.Entity("InfoWeb.Models.ContaPagar", b =>
                {
                    b.Property<int>("pag_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pag_codigo"));

                    b.Property<int?>("cen_codigo")
                        .HasColumnType("int");

                    b.Property<int>("fpg_codigo")
                        .HasColumnType("int");

                    b.Property<int>("loj_codigo")
                        .HasColumnType("int");

                    b.Property<bool>("pag_debtesouraria")
                        .HasColumnType("bit");

                    b.Property<string>("pag_documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("pag_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtcadastro")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtcomp")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtlanc")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtpag")
                        .HasColumnType("date");

                    b.Property<DateTime>("pag_dtvenc")
                        .HasColumnType("date");

                    b.Property<string>("pag_historico")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<TimeSpan>("pag_hora")
                        .HasColumnType("time");

                    b.Property<string>("pag_id_refs")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("pag_numNfe")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("pag_situacao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("pag_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("pag_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<decimal>("pag_vlracresc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrdesc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrdoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrmulta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrpagar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pag_vlrpago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("pes_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("tes_codigo")
                        .HasColumnType("int");

                    b.HasKey("pag_codigo");

                    b.HasIndex("cen_codigo");

                    b.HasIndex("fpg_codigo");

                    b.ToTable("ContasPagar");
                });

            modelBuilder.Entity("InfoWeb.Models.FormaPag", b =>
                {
                    b.Property<int>("fpg_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fpg_codigo"));

                    b.Property<string>("fpg_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("fpg_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("fpg_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("fpg_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("fpg_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("fpg_codigo");

                    b.ToTable("FormasPag");
                });

            modelBuilder.Entity("InfoWeb.Models.GrupoPro", b =>
                {
                    b.Property<int>("gru_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gru_codigo"));

                    b.Property<string>("gru_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("gru_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("gru_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("gru_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("gru_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("gru_codigo");

                    b.ToTable("GruposPro");
                });

            modelBuilder.Entity("InfoWeb.Models.Marca", b =>
                {
                    b.Property<int>("mar_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mar_codigo"));

                    b.Property<string>("mar_descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("mar_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("mar_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("mar_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("mar_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("mar_codigo");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("InfoWeb.Models.Produto", b =>
                {
                    b.Property<int>("pro_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pro_codigo"));

                    b.Property<DateTime>("cen_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("cen_dtcadastro")
                        .HasColumnType("date");

                    b.Property<int>("cen_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("cen_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<int>("gru_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("ica_codigo")
                        .HasColumnType("int");

                    b.Property<int>("mar_codigo")
                        .HasColumnType("int");

                    b.Property<int>("pes_codigo")
                        .HasColumnType("int");

                    b.Property<string>("pro_codigoean")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("pro_descfiscal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("pro_descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("pro_genero")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("pro_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pro_ncm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("pro_observacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("pro_prccompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pro_prccomprant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pro_prccusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pro_prctransf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("pro_referencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("pro_situacao")
                        .HasColumnType("bit");

                    b.Property<string>("unidade")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("pro_codigo");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("InfoWeb.Models.Tesouraria", b =>
                {
                    b.Property<int>("tes_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tes_codigo"));

                    b.Property<int?>("cen_codigo")
                        .HasColumnType("int");

                    b.Property<int>("fpg_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("loj_codigo")
                        .HasColumnType("int");

                    b.Property<int>("pag_codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("tes_data")
                        .HasColumnType("date");

                    b.Property<DateTime>("tes_datavenc")
                        .HasColumnType("date");

                    b.Property<string>("tes_doctitulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("tes_documento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("tes_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("tes_dtcadastro")
                        .HasColumnType("date");

                    b.Property<string>("tes_historico")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<TimeSpan>("tes_hora")
                        .HasColumnType("time");

                    b.Property<string>("tes_tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("tes_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("tes_usu_cadastro")
                        .HasColumnType("int");

                    b.Property<decimal>("tes_valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("tes_codigo");

                    b.ToTable("Tesourarias");
                });

            modelBuilder.Entity("InfoWeb.Models.Usuario", b =>
                {
                    b.Property<int>("usu_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usu_codigo"));

                    b.Property<int>("loj_codigo")
                        .HasColumnType("int");

                    b.Property<string>("usu_apelido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("usu_cargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("usu_cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("usu_dtalteracao")
                        .HasColumnType("date");

                    b.Property<DateTime>("usu_dtcadastro")
                        .HasColumnType("date");

                    b.Property<string>("usu_email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("usu_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("usu_is_staff")
                        .HasColumnType("bit");

                    b.Property<string>("usu_nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("usu_situacao")
                        .HasColumnType("bit");

                    b.Property<int>("usu_usu_alteracao")
                        .HasColumnType("int");

                    b.Property<int>("usu_usu_cadastro")
                        .HasColumnType("int");

                    b.HasKey("usu_codigo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("InfoWeb.Models.ContaPagar", b =>
                {
                    b.HasOne("InfoWeb.Models.CentroCusto", null)
                        .WithMany()
                        .HasForeignKey("cen_codigo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InfoWeb.Models.FormaPag", null)
                        .WithMany()
                        .HasForeignKey("fpg_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
